config/urls.py
from django.conf import settings
from django.urls import include, path
from django.conf.urls.static import static
from django.contrib import admin
from django.views import defaults as default_views


urlpatterns = [

    # Admin
    path('jet/', include('jet.urls', 'jet')),
    path('jet/dashboard/', include('jet.dashboard.urls', 'jet-dashboard')),
    path(settings.ADMIN_URL, admin.site.urls),

    path("accounts/", include("allauth.urls")),
    path('auth/', include('rest_auth.urls')),
    path('auth/registration/', include('rest_auth.registration.urls')),

    path('', include('tratum.webclient.urls'), name='webclient'),
    path('api/', include('tratum.api.urls'), name="api"),
    path('business-info/', include('tratum.business_info.urls'), name='business_info'),
    path('chaining/', include('smart_selects.urls')),
    path('document-manager/', include('tratum.document_manager.urls'), name='document_manager'),
    path('reports/', include('tratum.reports.urls', namespace='reports')),
    path('store/', include('tratum.store.urls'), name='store'),
    path('users/', include('tratum.users.urls'), name='users'),

] + static(
    settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
)

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

tratum/api/urls.py
# -*- coding: utf-8 -*-
from django.urls import path, include
from . import views

app_name = 'api'
urlpatterns = [
    path('api-key/', views.ApiKeyDetailView.as_view(), name='api-key'),
    path('users/', include('tratum.users.urls'), name='users'),
    path('document-manager/', include('tratum.document_manager.urls'), name='document_manager'),
    path('store/', include('tratum.store.urls'), name='store')
]

tratum/document_manager/urls.py
from django.urls import path

from .views import (
    DocumentFieldList,
    DocumentFieldDetail,
    DocumentSectionList,
    DocumentSectionDetail,
    DocumentSectionFieldsList,
    ProcessDocumentView,
    SaveAnswersView,
    DocumentList,
    CategoryRootList,
    CategoryChildrenList,
    FinishDocumentView,
    UserDocumentContentView,
    MainDocumentList,
    LinkedFieldView,
    ChangeAdminOrder,
    ChangeAdminOptionOrder
)

app_name = 'document_manager'

urlpatterns = [
    path(
        'document-fields/',
        DocumentFieldList.as_view(),
        name='document-fields'
    ),
    path(
        'document-fields/<slug:slug>/',
        DocumentFieldDetail.as_view(),
        name='document-field'
    ),
    path(
        'document-sections/',
        DocumentSectionList.as_view(),
        name='document-sections'
    ),
    path(
        'document-sections/<slug:slug>/',
        DocumentSectionDetail.as_view(),
        name='document-section'
    ),
    path(
        'document-sections/<slug:slug>/section-fields/',
        DocumentSectionFieldsList.as_view(),
        name='document-section-fields'
    ),
    path(
        'document-options/<int:pk>/linked-fields/',
        LinkedFieldView.as_view(),
        name='document-option'
    ),
    path(
        'finish/',
        FinishDocumentView.as_view(),
        name='finish'
    ),
    path(
        'process/',
        ProcessDocumentView.as_view(),
        name='process'
    ),
    path(
        'save-preview/',
        SaveAnswersView.as_view(),
        name='save-preview'
    ),
    path(
        'form-preview/',
        UserDocumentContentView.as_view(),
        name='form-preview'
    ),
    path(
        'finish/',
        FinishDocumentView.as_view(),
        name='finish'
    ),
    path(
        'documents/',
        MainDocumentList.as_view(),
        name='main-document-list'
    ),
    path(
        'documents/<slug:slug>/',
        DocumentList.as_view(),
        name='document-list'
    ),
    path(
        'categories/',
        CategoryRootList.as_view(),
        name='categories-root-list'
    ),
    path(
        'change-admin-order/',
        ChangeAdminOrder.as_view(),
        name='change-admin-order'
    ),
    path(
        'change-admin-option-order/',
        ChangeAdminOptionOrder.as_view(),
        name='change-admin-option-order'
    ),
    path(
        'categories/<slug:slug>/children/',
        CategoryChildrenList.as_view(),
        name='categories-children-list'
    ),
]

tratum/store/urls.py
from django.urls import path

from . import views

app_name = 'store'

urlpatterns = [
    path(
        'document-bundles/',
        views.DocumentBundleList.as_view(),
        name='document-bundles'
    ),
    path(
        'create-user-document/',
        views.CreateUserDocument.as_view(),
        name='create-user-document'
    ),
    path(
        'create-user-bundle/',
        views.CreateUserBundle.as_view(),
        name='create_user_bundle'
    ),
    path(
        'user-document/<slug:identifier>/',
        views.UserDocumentDetailView.as_view(),
        name='user-document'
    ),
    path(
        'checkout/',
        views.Checkout.as_view(),
        name='checkout'
    ),
    path(
        'confirmation/',
        views.Checkout.confirmation,
        name='checkout-confirmation'
    ),
]

tratum/users/urls.py
# -*- coding: utf-8 -*-
from django.urls import path

from .views import (
    CompanyUpdate,
    FacebookAuth,
    GoogleAuth,
    SectorList,
    UserChangeEmail,
    UserChangePassword,
    UserDetail,
    UserNameUpdate,
    UserProfessionUpdate
)

app_name = 'users'

urlpatterns = [
    path('auth/facebook/', FacebookAuth.as_view(), name='fb_login'),
    path('auth/google/', GoogleAuth.as_view(), name='gl_login'),
    path('auth/user/', UserDetail.as_view(), name='user-detail'),
    path('profile/<int:pk>/', UserNameUpdate.as_view(), name='user_name_update'),
    path('profile/profession/', UserProfessionUpdate.as_view(), name='user_profession_update'),
    path('change-email/', UserChangeEmail.as_view(), name='user_change_email'),
    path('change-password/', UserChangePassword.as_view(), name='user_change_password'),
    path('sectors/', SectorList.as_view(), name='sector_list'),
    path('company-update/', CompanyUpdate.as_view(), name='company_update'),
]

tratum/webclient/urls.py
import mptt_urls

from django.conf.urls import url
from django.contrib.auth import views as auth_views
from django.urls import path
from . import views

from tratum.document_manager.models import Category
from tratum.document_manager.views import category


app_name = 'webclient'
urlpatterns = [
    path(
        '',
        views.HomePageView.as_view(),
        name='home'
    ),
    path(
        'login/',
        views.LoginView.as_view(),
        name='login'
    ),
    path(
        'logout/',
        auth_views.LogoutView.as_view(next_page="/"),
        name='logout'
    ),
    path(
        'signup/',
        views.SignupView.as_view(),
        name='signup'
    ),
    path(
        'policies/<str:type>/',
        views.PoliciesView.as_view(),
        name='policies'
    ),
    path(
        'validate-terms/',
        views.ValidateTerms.as_view(),
        name="validate-terms"
    ),
    path(
        'faq/',
        views.FAQView.as_view(),
        name="faq"
    ),
    path(
        'glosario/',
        views.GlossaryView.as_view(),
        name="glossary"
    ),
    path(
        'about-us/',
        views.AboutUsView.as_view(),
        name='about-us'
    ),
    path(
        'my-documents/<slug:identifier>/edit/',
        views.UserDocumentView.as_view(),
        name='user-document'
    ),
    path(
        'my-documents/<slug:identifier>/process/',
        views.UserDocumentProcessPreviewView.as_view(),
        name='user-document-process'
    ),
    path(
        'my-documents/<slug:identifier>/preview/',
        views.UserDocumentPreviewView.as_view(),
        name='user-document-preview'
    ),
    path(
        'profile/',
        views.ProfileView.as_view(),
        name='profile'
    ),
    path(
        'my-documents/',
        views.UserDocumentsView.as_view(),
        name='user-documents'
    ),
    path(
        'activate/<token>/<pk>/',
        views.activate,
        name='activate'
    ),
    path(
        'contact-form/',
        views.ContactFormView.as_view(),
        name='contact-form'
    ),
    url(
        r'^documents/(?P<path>.*)',
        mptt_urls.view(model=Category, view=category, slug_field='slug'),
        name='category_documents'
    ),
    path(
        'creacion-empresa/',
        views.CreacionEmpresa.as_view(),
        name="creacion_empresa"
    ),
    path(
        'gestion-contractual/',
        views.GestionContractual.as_view(),
        name="gestion_contractual"
    ),
    path(
        'gestion-empresarial/',
        views.GestionEmpresarial.as_view(),
        name="gestion_empresarial"
    ),
    path(
        'negocios-asuntos-personales/',
        views.NegociosAsuntosPersonales.as_view(),
        name="negocios_asuntos_personales"
    ),
    path(
        'contact-form-landing/',
        views.send_contact_email,
        name="contact_form_email"
    ),
    path(
        'register-form-landing/',
        views.send_register_email,
        name="register_email"
    ),
    path(
        'registro-evento/',
        views.LandingForm.as_view(),
        name="landing_form"
    ),
    path('plans', views.SubscriptionList.as_view(), name='plans')
]

tratum/api/models.py
# -*- coding: utf-8 -*-
import uuid
from django.db import models


class APIKey(models.Model):
    """
    Clase para manejar las restricciones en las API's
    """

    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)

    name = models.CharField(max_length=50, unique=True)
    key = models.CharField(max_length=40, unique=True)

    class Meta:
        verbose_name = "Llave de API"
        verbose_name_plural = "Llaves de API"
        ordering = ['-created']
        app_label = "api"

    def __str__(self):
        return self.name

tratum/api/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from rest_framework import generics, status
from rest_framework.permissions import AllowAny
from rest_framework.response import Response
from .models import APIKey
from .serializers import ApiKeySerializer


class ApiKeyDetailView(generics.ListAPIView):
    """
    API para obtener la api key
    """

    serializer_class = ApiKeySerializer
    permission_classes = (AllowAny,)

    def get(self, request, format=None):
        if APIKey.objects.filter(name='web').exists():
            serializer = ApiKeySerializer(APIKey.objects.get(name='web'), many=False)
        else:
            return Response({
                'detail': 'Ocurrió un error al obtener el objeto'
            }, status=status.HTTP_500_INTERNAL_SERVER_ERROR)
        return Response(serializer.data)

tratum/business_info/views.py
from rest_framework import generics

from .models import (
    Policy,
    FAQCategory
)
from .serializers import (
    PolicySerializer,
    FAQCategorySerializer
)


class PolicyList(generics.ListAPIView):
    queryset = Policy.objects.all()
    serializer_class = PolicySerializer


class FAQCategoryList(generics.ListAPIView):
    queryset = FAQCategory.objects.all()
    serializer_class = FAQCategorySerializer

tratum/reports/views.py
from io import BytesIO
import json

from django.http import HttpResponse

from django.template.loader import get_template
from django.views.generic.base import View

from xhtml2pdf import pisa

from .resources import (
    DocumentResource,
    CategoryResource,
    DocumentBundleResource,
    InvoiceResource
)


class DocumentExport(View):

    def post(self, request, *args, **kwargs):
        resource = DocumentResource()
        dataset = resource.export()
        if request.POST.get('CSV', None):
            export_type = dataset.csv
            content_type = 'text/csv'
            format = 'csv'
        elif request.POST.get('XLS', None):
            export_type = dataset.xls
            content_type = 'application/vnd.ms-excel'
            format = 'xls'
        elif request.POST.get('PDF', None):
            template_path = 'admin/document_reports/pdf_skeleton.html'

            context = {
                'summary': json.loads(dataset.json)
            }

            template = get_template(template_path)
            html = template.render(context)

            result = BytesIO()
            pdf = pisa.pisaDocument(BytesIO(html.encode("utf-8")), dest=result)
            if not pdf.err:
                return HttpResponse(result.getvalue(), content_type='application/pdf')
            else:
                return HttpResponse('Errors')

        response = HttpResponse(export_type, content_type=content_type)
        response['Content-Disposition'] = 'attachment; filename="report.{}"'.format(format)
        return response


class CategoryExport(View):

    def post(self, request, *args, **kwargs):
        resource = CategoryResource()
        dataset = resource.export()
        if request.POST.get('CSV', None):
            export_type = dataset.csv
            content_type = 'text/csv'
            format = 'csv'
        elif request.POST.get('XLS', None):
            export_type = dataset.xls
            content_type = 'application/vnd.ms-excel'
            format = 'xls'
        elif request.POST.get('PDF', None):
            template_path = 'admin/category_reports/pdf_skeleton.html'

            context = {
                'summary': json.loads(dataset.json)
            }

            template = get_template(template_path)
            html = template.render(context)

            result = BytesIO()
            pdf = pisa.pisaDocument(BytesIO(html.encode("utf-8")), dest=result)
            if not pdf.err:
                return HttpResponse(result.getvalue(), content_type='application/pdf')
            else:
                return HttpResponse('Errors')

        response = HttpResponse(export_type, content_type=content_type)
        response['Content-Disposition'] = 'attachment; filename="report.{}"'.format(format)
        return response


class DocumentBundleExport(View):

    def post(self, request, *args, **kwargs):
        resource = DocumentBundleResource()
        dataset = resource.export()
        if request.POST.get('CSV', None):
            export_type = dataset.csv
            content_type = 'text/csv'
            format = 'csv'
        elif request.POST.get('XLS', None):
            export_type = dataset.xls
            content_type = 'application/vnd.ms-excel'
            format = 'xls'
        elif request.POST.get('PDF', None):
            template_path = 'admin/bundle_reports/pdf_skeleton.html'

            context = {
                'summary': json.loads(dataset.json)
            }

            template = get_template(template_path)
            html = template.render(context)

            result = BytesIO()
            pdf = pisa.pisaDocument(BytesIO(html.encode("utf-8")), dest=result)
            if not pdf.err:
                return HttpResponse(result.getvalue(), content_type='application/pdf')
            else:
                return HttpResponse('Errors')

        response = HttpResponse(export_type, content_type=content_type)
        response['Content-Disposition'] = 'attachment; filename="report.{}"'.format(format)
        return response


class InvoiceExport(View):

    def post(self, request, *args, **kwargs):
        resource = InvoiceResource()
        dataset = resource.export()
        if request.POST.get('CSV', None):
            export_type = dataset.csv
            content_type = 'text/csv'
            format = 'csv'
        elif request.POST.get('XLS', None):
            export_type = dataset.xls
            content_type = 'application/vnd.ms-excel'
            format = 'xls'
        elif request.POST.get('PDF', None):
            template_path = 'admin/user_reports/pdf_skeleton.html'

            context = {
                'summary': json.loads(dataset.json)
            }

            template = get_template(template_path)
            html = template.render(context)

            result = BytesIO()
            pdf = pisa.pisaDocument(BytesIO(html.encode("utf-8")), dest=result)
            if not pdf.err:
                return HttpResponse(result.getvalue(), content_type='application/pdf')
            else:
                return HttpResponse('Errors')

        response = HttpResponse(export_type, content_type=content_type)
        response['Content-Disposition'] = 'attachment; filename="report.{}"'.format(format)
        return response

tratum/utils/views.py
from django.contrib.auth.tokens import PasswordResetTokenGenerator
from django.utils import six


class AccountActivationTokenGenerator(PasswordResetTokenGenerator):
    def _make_hash_value(self, user, timestamp):
        return (
            six.text_type(user.pk) + six.text_type(timestamp) +
            six.text_type(user.email)
        )

account_activation_token = AccountActivationTokenGenerator()

tratum/templates/document_form/document_detail.html
{% load static %}
{% load embed_video_tags %}

<!doctype html>
<html lang="es">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="shortcut icon" href="{% static 'img/logo/favicon.png' %}">
    <title>Tratum</title>
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css"
    crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.1.0/css/all.css"
    integrity="sha384-lKuwvrZot6UHsBSfcMvOkWwlCMgc0TaWr+30HWe3a4ltaBwTZhyTEggF5tJv8tbt"
    crossorigin="anonymous">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/pickadate.js/3.5.6/compressed/themes/default.css" rel="stylesheet">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/pickadate.js/3.5.6/compressed/themes/default.date.css" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Titillium+Web:300,400" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css" type="text/css">
    <link href="{% static 'css/form.css' %}" rel="stylesheet">
    <script>
      !function(f,b,e,v,n,t,s)
      {if(f.fbq)return;n=f.fbq=function(){n.callMethod?
      n.callMethod.apply(n,arguments):n.queue.push(arguments)};
      if(!f._fbq)f._fbq=n;n.push=n;n.loaded=!0;n.version='2.0';
      n.queue=[];t=b.createElement(e);t.async=!0;
      t.src=v;s=b.getElementsByTagName(e)[0];
      s.parentNode.insertBefore(t,s)}(window, document,'script',
      'https://connect.facebook.net/en_US/fbevents.js');
      fbq('init', '213230306721780');
      fbq('track', 'PageView');
    </script>
    <noscript><img height="1" width="1" style="display:none"
      src="https://www.facebook.com/tr?id=213230306721780&ev=PageView&noscript=1"
    /></noscript>
  </head>

  <body>
    <div
      id="doc-info"
      data-uuid="{{identifier}}"
      data-apikey="{{Api_Key}}"
      data-csrftoken="{{csrf_token}}"></div>

    <div class="row main">
      <div class="col-lg-5 form-col" style="z-index: 9999999;">
          <div class="upform">
            <a href="{% url 'webclient:user-documents' %}" class="col">
              <img class="logo" src="{% static 'img/logo/tratum.png' %}" href="/">
            </a>
            <form method="POST" action="{% url 'document_manager:process' %}" id="document-form">
              <input type="hidden" name="identifier" value="{{identifier}}" />
              <div class="upform-header"></div>
              <div class="upform-main">
                {% for field in object.get_fields %}
                  {% include 'document_form/fields.html' %}
                  {% if field.field_type == field.LIST %}
                    <div class="list-fields">
                      {% for field in field.field_group.all %}
                        {% include 'document_form/fields.html' %}
                      {% endfor %}
                    </div>
                  {% endif %}
                {% endfor %}

                <div class="sections col mt-5">
                  <h3 class="mb-3">Secciones opcionales disponibles: </h3>
                  {% for s in object.get_sections %}
                    <div class="col">
                      <input type="checkbox" name="{{s.formated_slug}}" class="section-item mb-3"> {{s.display_name}}</input>
                      {% if s.help_text %}
                        <i class="fas fa-question-circle float-right" data-toggle="tooltip" data-placement="right" title="{{s.help_text}}"></i>
                      {% endif %}
                    </div>
                    <div class="section-fields" data-section="{{s.formated_slug}}">
                      {% for field in s.get_fields %}
                        {% include 'document_form/fields.html' %}
                      {% endfor %}
                    </div>

                  {% empty %}
                    <p>Este documento no contiene secciones opcionales</p>
                  {% endfor %}
                </div>
              </div>

            </form>
          </div>
          <div class="upform-footer" id="mobile-generate-doc">
             <a href="{% url 'webclient:user-document-process' identifier %}" class="btn btn-primary btn-lg preview">Generar documento</a>
          </div>
      </div>
      <div class="col-lg-7 p-0">
        <div class="info-col doc-preview-col">
              <div class="document-preview" id="content-preview" data-name="{{object.document.name}}">
              </div>
              <div class="upform-footer">
                <a href="{% url 'webclient:user-document-process' identifier %}" class="btn btn-primary btn-lg preview">Generar documento</a>
              </div>
        </div>

      </div>

    </div>

    <div class="modal fade" id="videoModal" tabindex="-1" role="dialog" aria-labelledby="videoModal" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Video explicativo</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    ...
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                </div>
            </div>
        </div>
    </div>

    <div class="modal fade" id="loadingModal" tabindex="-1" role="dialog" aria-labelledby="loadingModal" aria-hidden="true">
        <div class="modal-dialog h-100 d-flex flex-column justify-content-center my-0" role="document">
            <div class="modal-content">
                <div class="modal-body">
                  <img src="{% static 'img/loadingCard.gif' %}" width="40px" class="text-center"/>
                  <span class="float-right loading">Procesando formulario...</span>
                </div>
            </div>
        </div>
    </div>

    <script src="//ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://unpkg.com/axios/dist/axios.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/jquery-scrollTo/2.1.2/jquery.scrollTo.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/pickadate.js/3.5.6/compressed/legacy.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/pickadate.js/3.5.6/compressed/picker.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/pickadate.js/3.5.6/compressed/picker.date.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/pickadate.js/3.5.6/compressed/picker.time.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/pickadate.js/3.5.6/compressed/translations/es_ES.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-price-format/2.2.0/jquery.priceformat.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    <script type="application/javascript" src="{% static 'js/jquery.textAdjust.min.js' %}"></script>
    <script src="{% static 'js/form.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/pdfRender.js' %}"></script>
  </body>
</html>

tratum/templates/document_form/document_preview.html
{% extends 'webclient/base.html' %}
{% load humanize %}
{% load static %}
{% load fieldformatter %}

{% block extra_css %}
  <link rel="stylesheet" href="{% static 'css/preview.css' %}">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jquery-confirm/3.3.0/jquery-confirm.min.css">
{% endblock %}

{% block nav_class %}
    class="navbar scrolled"
{% endblock %}

{% block content %}
    <div 
      id="doc-info"
      data-uuid="{{object.identifier}}"
      data-apikey="{{Api_Key}}"
      data-csrftoken="{{csrf_token}}"></div>
    <div class="container">
        <div class="row">
            <div class="col-md-8">
                <div class="document-preview" id="content-preview" data-name="{{object.document.name}}">
                    {{document_content}}
                </div>
            </div>
            {% if object.status == object.is_expired %}
                <div class="col-md-4 mt-4">
                    <span>El tiempo límite para exportar el documento a caducado</span>
                </div>
            {% else %}
                {% if object.status == object.FINISHED %}
                    <div class="col-md-4 mt-4">
                        <a href="{% url 'webclient:user-documents' %}" class="underline">Ver mis documentos</a></br>
                        <button class="action-button__primary blue link-button" data-href="{{object.pdf_file.url}}">Descargar PDF</button></br>
                        <button class="action-button__primary blue link-button" data-href="{% if object.word_file%}{{object.word_file.url}}{% endif %}">Descargar DOC</button>
                    </div>
                {% else %}
                    <div class="col-md-4">
                        <button class="action-button__primary blue finish">Finalizar</button>
                        <button class="action-button__primary blank link-button" data-href="{{object.get_absolute_url}}">Editar</button>
                    </div>
                {% endif %}                
            {% endif %}    
        </div>
    </div>
{% endblock%}


{% block extra_js %}
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-confirm/3.3.0/jquery-confirm.min.js"></script>
    <script type="text/javascript" src="{% static 'js/html-docx.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/preview.js' %}"></script>    
    <script type="text/javascript" src="{% static 'js/pdfRender.js' %}"></script>    
    <script src="https://fastcdn.org/FileSaver.js/1.1.20151003/FileSaver.min.js"></script>
    <script type="text/javascript" src="{% static 'js/docRender.js' %}"></script> 
{% endblock %}