config/urls.py
from django.conf import settings
from django.urls import include, path
from django.conf.urls.static import static
from django.contrib import admin
from django.views import defaults as default_views


urlpatterns = [

    # Admin
    path('jet/', include('jet.urls', 'jet')),
    path('jet/dashboard/', include('jet.dashboard.urls', 'jet-dashboard')),
    path(settings.ADMIN_URL, admin.site.urls),

    path("accounts/", include("allauth.urls")),
    path('auth/', include('rest_auth.urls')),
    path('auth/registration/', include('rest_auth.registration.urls')),

    path('', include('tratum.webclient.urls'), name='webclient'),
    path('api/', include('tratum.api.urls'), name="api"),
    path('business-info/', include('tratum.business_info.urls'), name='business_info'),
    path('chaining/', include('smart_selects.urls')),
    path('document-manager/', include('tratum.document_manager.urls'), name='document_manager'),
    path('reports/', include('tratum.reports.urls', namespace='reports')),
    path('store/', include('tratum.store.urls'), name='store'),
    path('users/', include('tratum.users.urls'), name='users'),

] + static(
    settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
)

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

tratum/api/urls.py
# -*- coding: utf-8 -*-
from django.urls import path, include
from . import views

app_name = 'api'
urlpatterns = [
    path('api-key/', views.ApiKeyDetailView.as_view(), name='api-key'),
    path('users/', include('tratum.users.urls'), name='users'),
    path('document-manager/', include('tratum.document_manager.urls'), name='document_manager'),
    path('store/', include('tratum.store.urls'), name='store')
]

tratum/store/urls.py
from django.urls import path

from . import views

app_name = 'store'

urlpatterns = [
    path(
        'document-bundles/',
        views.DocumentBundleList.as_view(),
        name='document-bundles'
    ),
    path(
        'create-user-document/',
        views.CreateUserDocument.as_view(),
        name='create-user-document'
    ),
    path(
        'create-user-bundle/',
        views.CreateUserBundle.as_view(),
        name='create_user_bundle'
    ),
    path(
        'user-document/<slug:identifier>/',
        views.UserDocumentDetailView.as_view(),
        name='user-document'
    ),
    path(
        'checkout/',
        views.Checkout.as_view(),
        name='checkout'
    ),
    path(
        'confirmation/',
        views.Checkout.confirmation,
        name='checkout-confirmation'
    ),
]

tratum/users/urls.py
# -*- coding: utf-8 -*-
from django.urls import path

from .views import (
    CompanyUpdate,
    FacebookAuth,
    GoogleAuth,
    SectorList,
    UserChangeEmail,
    UserChangePassword,
    UserDetail,
    UserNameUpdate,
    UserProfessionUpdate
)

app_name = 'users'

urlpatterns = [
    path('auth/facebook/', FacebookAuth.as_view(), name='fb_login'),
    path('auth/google/', GoogleAuth.as_view(), name='gl_login'),
    path('auth/user/', UserDetail.as_view(), name='user-detail'),
    path('profile/<int:pk>/', UserNameUpdate.as_view(), name='user_name_update'),
    path('profile/profession/', UserProfessionUpdate.as_view(), name='user_profession_update'),
    path('change-email/', UserChangeEmail.as_view(), name='user_change_email'),
    path('change-password/', UserChangePassword.as_view(), name='user_change_password'),
    path('sectors/', SectorList.as_view(), name='sector_list'),
    path('company-update/', CompanyUpdate.as_view(), name='company_update'),
]

tratum/webclient/urls.py
import mptt_urls

from django.conf.urls import url
from django.contrib.auth import views as auth_views
from django.urls import path
from . import views

from tratum.document_manager.models import Category
from tratum.document_manager.views import category


app_name = 'webclient'
urlpatterns = [
    path(
        '',
        views.HomePageView.as_view(),
        name='home'
    ),
    path(
        'login/',
        views.LoginView.as_view(),
        name='login'
    ),
    path(
        'logout/',
        auth_views.LogoutView.as_view(next_page="/"),
        name='logout'
    ),
    path(
        'signup/',
        views.SignupView.as_view(),
        name='signup'
    ),
    path(
        'policies/<str:type>/',
        views.PoliciesView.as_view(),
        name='policies'
    ),
    path(
        'validate-terms/',
        views.ValidateTerms.as_view(),
        name="validate-terms"
    ),
    path(
        'faq/',
        views.FAQView.as_view(),
        name="faq"
    ),
    path(
        'glosario/',
        views.GlossaryView.as_view(),
        name="glossary"
    ),
    path(
        'about-us/',
        views.AboutUsView.as_view(),
        name='about-us'
    ),
    path(
        'my-documents/<slug:identifier>/edit/',
        views.UserDocumentView.as_view(),
        name='user-document'
    ),
    path(
        'my-documents/<slug:identifier>/process/',
        views.UserDocumentProcessPreviewView.as_view(),
        name='user-document-process'
    ),
    path(
        'my-documents/<slug:identifier>/preview/',
        views.UserDocumentPreviewView.as_view(),
        name='user-document-preview'
    ),
    path(
        'profile/',
        views.ProfileView.as_view(),
        name='profile'
    ),
    path(
        'my-documents/',
        views.UserDocumentsView.as_view(),
        name='user-documents'
    ),
    path(
        'activate/<token>/<pk>/',
        views.activate,
        name='activate'
    ),
    path(
        'contact-form/',
        views.ContactFormView.as_view(),
        name='contact-form'
    ),
    url(
        r'^documents/(?P<path>.*)',
        mptt_urls.view(model=Category, view=category, slug_field='slug'),
        name='category_documents'
    ),
    path(
        'creacion-empresa/',
        views.CreacionEmpresa.as_view(),
        name="creacion_empresa"
    ),
    path(
        'gestion-contractual/',
        views.GestionContractual.as_view(),
        name="gestion_contractual"
    ),
    path(
        'gestion-empresarial/',
        views.GestionEmpresarial.as_view(),
        name="gestion_empresarial"
    ),
    path(
        'negocios-asuntos-personales/',
        views.NegociosAsuntosPersonales.as_view(),
        name="negocios_asuntos_personales"
    ),
    path(
        'contact-form-landing/',
        views.send_contact_email,
        name="contact_form_email"
    ),
    path(
        'register-form-landing/',
        views.send_register_email,
        name="register_email"
    ),
    path(
        'registro-evento/',
        views.LandingForm.as_view(),
        name="landing_form"
    ),
    path('plans', views.SubscriptionList.as_view(), name='plans')
]

tratum/api/models.py
# -*- coding: utf-8 -*-
import uuid
from django.db import models


class APIKey(models.Model):
    """
    Clase para manejar las restricciones en las API's
    """

    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)

    name = models.CharField(max_length=50, unique=True)
    key = models.CharField(max_length=40, unique=True)

    class Meta:
        verbose_name = "Llave de API"
        verbose_name_plural = "Llaves de API"
        ordering = ['-created']
        app_label = "api"

    def __str__(self):
        return self.name

tratum/reports/models.py
from tratum.document_manager.models import Document, Category
from tratum.store.models import DocumentBundle, Invoice


class DocumentSaleSummary(Document):
    class Meta:
        proxy = True
        verbose_name = 'Reporte de venta de documentos'
        verbose_name_plural = 'Reportes de venta de documentos'


class UserDocumentsSummary(Invoice):
    class Meta:
        proxy = True
        verbose_name = 'Reporte de compras de documentos de clientes'
        verbose_name_plural = 'Reportes de compras de documentos de clientes'


class CategorySaleSummary(Category):
    class Meta:
        proxy = True
        verbose_name = 'Reporte de ventas documentos por categoría'
        verbose_name_plural = 'Reportes de ventas documentos por categoría'


class BundleSaleSummary(DocumentBundle):
    class Meta:
        proxy = True
        verbose_name = 'Reporte de ventas de paquetes'
        verbose_name_plural = 'Reportes de ventas de paquetes'

tratum/business_info/forms.py
from django import forms
from django.core.files.images import get_image_dimensions
from .models import SliderItem, SiteConfig


class SliderItemForm(forms.ModelForm):

    class Meta:
        model = SliderItem
        fields = '__all__'

    def clean_image(self):
        picture = self.cleaned_data.get("image")
        if not picture:
            raise forms.ValidationError("La imagen es requerida")
        else:
            w, h = get_image_dimensions(picture)
            if w != 1920:
                raise forms.ValidationError("La imagen tiene un ancho de %i pixels, se requieren 1920 pixeles." % w)
            if h != 1080:
                raise forms.ValidationError("La imagen tiene un alto de %i pixels, se requieren 1080 pixeles" % h)
        return picture


class SiteConfigForm(forms.ModelForm):

    class Meta:
        model = SiteConfig
        fields = '__all__'

    def clean_about_page_image(self):
        picture = self.cleaned_data.get("about_page_image")
        if not picture:
            raise forms.ValidationError("La imagen es requerida")
        else:
            w, h = get_image_dimensions(picture)
            if w != 800:
                raise forms.ValidationError("La imagen tiene un ancho de %i pixels, se requieren 800 pixeles." % w)
            if h != 1000:
                raise forms.ValidationError("La imagen tiene un alto de %i pixels, se requieren 1000 pixeles" % h)
        return picture

tratum/api/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from rest_framework import generics, status
from rest_framework.permissions import AllowAny
from rest_framework.response import Response
from .models import APIKey
from .serializers import ApiKeySerializer


class ApiKeyDetailView(generics.ListAPIView):
    """
    API para obtener la api key
    """

    serializer_class = ApiKeySerializer
    permission_classes = (AllowAny,)

    def get(self, request, format=None):
        if APIKey.objects.filter(name='web').exists():
            serializer = ApiKeySerializer(APIKey.objects.get(name='web'), many=False)
        else:
            return Response({
                'detail': 'Ocurrió un error al obtener el objeto'
            }, status=status.HTTP_500_INTERNAL_SERVER_ERROR)
        return Response(serializer.data)

tratum/business_info/views.py
from rest_framework import generics

from .models import (
    Policy,
    FAQCategory
)
from .serializers import (
    PolicySerializer,
    FAQCategorySerializer
)


class PolicyList(generics.ListAPIView):
    queryset = Policy.objects.all()
    serializer_class = PolicySerializer


class FAQCategoryList(generics.ListAPIView):
    queryset = FAQCategory.objects.all()
    serializer_class = FAQCategorySerializer

tratum/reports/views.py
from io import BytesIO
import json

from django.http import HttpResponse

from django.template.loader import get_template
from django.views.generic.base import View

from xhtml2pdf import pisa

from .resources import (
    DocumentResource,
    CategoryResource,
    DocumentBundleResource,
    InvoiceResource
)


class DocumentExport(View):

    def post(self, request, *args, **kwargs):
        resource = DocumentResource()
        dataset = resource.export()
        if request.POST.get('CSV', None):
            export_type = dataset.csv
            content_type = 'text/csv'
            format = 'csv'
        elif request.POST.get('XLS', None):
            export_type = dataset.xls
            content_type = 'application/vnd.ms-excel'
            format = 'xls'
        elif request.POST.get('PDF', None):
            template_path = 'admin/document_reports/pdf_skeleton.html'

            context = {
                'summary': json.loads(dataset.json)
            }

            template = get_template(template_path)
            html = template.render(context)

            result = BytesIO()
            pdf = pisa.pisaDocument(BytesIO(html.encode("utf-8")), dest=result)
            if not pdf.err:
                return HttpResponse(result.getvalue(), content_type='application/pdf')
            else:
                return HttpResponse('Errors')

        response = HttpResponse(export_type, content_type=content_type)
        response['Content-Disposition'] = 'attachment; filename="report.{}"'.format(format)
        return response


class CategoryExport(View):

    def post(self, request, *args, **kwargs):
        resource = CategoryResource()
        dataset = resource.export()
        if request.POST.get('CSV', None):
            export_type = dataset.csv
            content_type = 'text/csv'
            format = 'csv'
        elif request.POST.get('XLS', None):
            export_type = dataset.xls
            content_type = 'application/vnd.ms-excel'
            format = 'xls'
        elif request.POST.get('PDF', None):
            template_path = 'admin/category_reports/pdf_skeleton.html'

            context = {
                'summary': json.loads(dataset.json)
            }

            template = get_template(template_path)
            html = template.render(context)

            result = BytesIO()
            pdf = pisa.pisaDocument(BytesIO(html.encode("utf-8")), dest=result)
            if not pdf.err:
                return HttpResponse(result.getvalue(), content_type='application/pdf')
            else:
                return HttpResponse('Errors')

        response = HttpResponse(export_type, content_type=content_type)
        response['Content-Disposition'] = 'attachment; filename="report.{}"'.format(format)
        return response


class DocumentBundleExport(View):

    def post(self, request, *args, **kwargs):
        resource = DocumentBundleResource()
        dataset = resource.export()
        if request.POST.get('CSV', None):
            export_type = dataset.csv
            content_type = 'text/csv'
            format = 'csv'
        elif request.POST.get('XLS', None):
            export_type = dataset.xls
            content_type = 'application/vnd.ms-excel'
            format = 'xls'
        elif request.POST.get('PDF', None):
            template_path = 'admin/bundle_reports/pdf_skeleton.html'

            context = {
                'summary': json.loads(dataset.json)
            }

            template = get_template(template_path)
            html = template.render(context)

            result = BytesIO()
            pdf = pisa.pisaDocument(BytesIO(html.encode("utf-8")), dest=result)
            if not pdf.err:
                return HttpResponse(result.getvalue(), content_type='application/pdf')
            else:
                return HttpResponse('Errors')

        response = HttpResponse(export_type, content_type=content_type)
        response['Content-Disposition'] = 'attachment; filename="report.{}"'.format(format)
        return response


class InvoiceExport(View):

    def post(self, request, *args, **kwargs):
        resource = InvoiceResource()
        dataset = resource.export()
        if request.POST.get('CSV', None):
            export_type = dataset.csv
            content_type = 'text/csv'
            format = 'csv'
        elif request.POST.get('XLS', None):
            export_type = dataset.xls
            content_type = 'application/vnd.ms-excel'
            format = 'xls'
        elif request.POST.get('PDF', None):
            template_path = 'admin/user_reports/pdf_skeleton.html'

            context = {
                'summary': json.loads(dataset.json)
            }

            template = get_template(template_path)
            html = template.render(context)

            result = BytesIO()
            pdf = pisa.pisaDocument(BytesIO(html.encode("utf-8")), dest=result)
            if not pdf.err:
                return HttpResponse(result.getvalue(), content_type='application/pdf')
            else:
                return HttpResponse('Errors')

        response = HttpResponse(export_type, content_type=content_type)
        response['Content-Disposition'] = 'attachment; filename="report.{}"'.format(format)
        return response

tratum/utils/views.py
from django.contrib.auth.tokens import PasswordResetTokenGenerator
from django.utils import six


class AccountActivationTokenGenerator(PasswordResetTokenGenerator):
    def _make_hash_value(self, user, timestamp):
        return (
            six.text_type(user.pk) + six.text_type(timestamp) +
            six.text_type(user.email)
        )

account_activation_token = AccountActivationTokenGenerator()

tratum/templates/store/checkout.html
{% extends 'webclient/base.html' %}
{% load humanize %}
{% load static %}

{% block nav_class %}
    class="navbar scrolled"
{% endblock %}

{% block content %}
<div class="container checkout-resume">
    <div class="row body-summary justify-content-between">
        <div class="col-md-8">
            <div class="row header">
                <div class="col-12">
                    <div class="row justify-content-around">
                        <div class="col-md-8">
                            <img src="{% static 'img/checkout.png' %}" width="40" height="40" alt="">
                            <span class="resume-title">Resumen de la compra</span>
                        </div>
                        {% if type == 'doc' %}
                            <div class="col-md-3">
                                <span class="resume-subtitle"></span>
                            </div>
                        {% else %}
                            <div class="col-md-3">
                                <span class="resume-subtitle">{{type}}</span>
                            </div>
                        {% endif %}
                    </div>
                </div>
            </div>
            <div class="row justify-content-between content">
                {% for doc in documents %}
                    <div class="col-md-5 doc-content">
                        <span class="doc-title">{{doc.name}}</span>
                        <p class="text-justify">{{doc.short_description|default:"Sin Descripción"}}</p>
                        <span class="doc-price">$ {{doc.price|intcomma|default:'0'}}</span>
                    </div>
                {% endfor %}
            </div>
        </div>
        <div class="col-md-4 pl-md-5">
            <div class="row price">
                <div class="col-12">
                    <span class="resume-title">Resumen del pedido:</span>
                    <div class="container-fluid content-resume mb-3">
                        <div class="row">
                            <div class="col-12 count-docs">
                                <span>
                                    {{documents.count}} DOCUMENTO{{ documents.count|pluralize:'S' }}
                                </span>
                            </div>
                        </div>
                        <div class="row total-price">
                            <div class="col-lg-4 align-self-center">
                                <span>Total</span>
                            </div>
                            <div class="col-lg-8 align-self-center">
                                <span style="float: right;">$ {{amount|intcomma}}</span>
                            </div>
                        </div>
                    </div>

                    <form method="POST" action="{{url}}">
                        {% csrf_token %}
                        <input name="merchantId" type="hidden" value="{{merchantId}}" >
                        <input name="accountId" type="hidden" value="{{accountId}}">
                        <input name="description" type="hidden" value="{{description}}">
                        <input name="referenceCode" type="hidden" value="{{referenceCode}}">
                        <input name="amount" type="hidden" value="{{amount}}">
                        <input name="tax" type="hidden" value="{{tax}}">
                        <input name="taxReturnBase" type="hidden" value="{{taxReturnBase}}">
                        <input name="currency" type="hidden" value="{{currency}}">
                        <input name="signature" type="hidden" value="{{signature}}">
                        <input name="test" type="hidden" value="{{test}}">
                        <input name="buyerEmail" type="hidden" value="{{buyerEmail}}">
                        <input name="responseUrl" type="hidden"  value="{{responseUrl}}" >
                        <input name="confirmationUrl" type="hidden" value="{{confirmationUrl}}">

                        <button class="btn btn-pay" type="submit">Continuar <i class="fas fa-greater-than"></i></button>
                    </form>
                </div>
            </div>
        </div>

    </div>
    <div class="row footer-summary mb-4">
        <div class="col-12 pay-methods">
            <span>Opciones de pago</span>
        </div>
        <div class="col-12 pay-container">
            <div class="container mb-3">
                <div class="row">
                    <div class="col-md-4">
                        <div class="col-12 pay-name">
                            <span>Tarjétas de crédito</span>
                        </div>
                        <div class="col-12">
                            <ul>
                                <li><img class="img-responsive" src="{% static 'img/pay-methods/Visa.png' %}" width="60" height="60" alt="visa logo" ></li>
                                <li><img class="img-responsive" src="{% static 'img/pay-methods/MasterCard.png' %}" width="60" height="60" alt="visa logo" ></li>
                                <li><img class="img-responsive" src="{% static 'img/pay-methods/Dinners.png' %}" width="60" height="60" alt="visa logo" ></li>
                                <li><img class="img-responsive" src="{% static 'img/pay-methods/American.png' %}" width="60" height="60" alt="visa logo" ></li>
                            </ul>
                        </div>
                    </div>
                    <div class="col-md-4">
                        <div class="col-12 pay-name">
                            <span>Efectivo</span>
                        </div>
                        <div class="col-12">
                            <ul>
                                <li><img class="img-responsive" src="{% static 'img/pay-methods/efecty.png' %}" width="60" height="60" alt="visa logo" ></li>
                                <li><img class="img-responsive" src="{% static 'img/pay-methods/SuRED.png' %}" width="60" height="60" alt="visa logo" ></li>
                                <li><img class="img-responsive" src="{% static 'img/pay-methods/Baloto.png' %}" width="60" height="60" alt="visa logo" ></li>
                            </ul>
                        </div>
                    </div>
                    <div class="col-md-4">
                        <div class="col-12 pay-name">
                            <span>Pago en bancos</span>
                        </div>
                        <div class="col-12">
                            <ul>
                                <li><img class="img-responsive" src="{% static 'img/pay-methods/Davivienda.png' %}" width="60" height="60" alt="visa logo" ></li>
                                <li><img class="img-responsive" src="{% static 'img/pay-methods/bancodebogota.png' %}" width="60" height="60" alt="visa logo" ></li>
                                <li><img class="img-responsive" src="{% static 'img/pay-methods/Bancolombia.png' %}" width="60" height="60" alt="visa logo" ></li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

{% block nav-script%}
{% endblock %}

tratum/templates/store/payment-resumen.html
{% extends 'webclient/base.html' %}
{% load humanize %}
{% load static %}

{% block nav_class %}
    class="navbar scrolled"
{% endblock %}

{% block content %}
<main class="row">
    <div class="container">
        <div class="content_payU">
            <h3>Resultados de tu Pago</h3>
            <table class="table table-hover">
                <thead>
                    <tr>
                        <th scope="col"></th>
                        <th scope="col">Detalle</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <th scope="row">Estado</th>
                        <td>
                            {% if transactionState == "4"%}
                                Aprobada
                            {% endif %}
                            {% if transactionState == "6"%}
                                Declinada
                            {% endif %}
                            {% if transactionState == "104"%}
                                Error
                            {% endif %}
                            {% if transactionState == "5"%}
                                Expirada
                            {% endif %}
                            {% if transactionState == "7"%}
                                Pendiente
                            {% endif %}
                            </td>
                    </tr>
                    <tr>
                        <th scope="row">Referencia</th>
                        <td>{{  referenceCode }}</td>
                    </tr>
                    <tr>
                        <th scope="row">Referencia payU</th>
                        <td>{{reference_pol}}</td>
                    </tr>
                    <tr>
                        <th scope="row">Valor Pagado</th>
                        <td>{{currency}} ${{  value|floatformat|intcomma }}</td>
                    </tr>
                    <tr>
                        <th scope="row">Método de pago</th>
                        <td>
                            {% if polPaymentMethodType == '2' %}
                                Tarjeta de crédito
                            {% endif %}
                            {% if polPaymentMethodType ==  '4' %}
                                PSE-Transferencias bancarias
                            {% endif %}
                            {% if polPaymentMethodType == '5' %}
                                Débito ACH
                            {% endif %}
                            {% if polPaymentMethodType == '6' %}
                                Tarjetas débito
                            {% endif %}
                            {% if polPaymentMethodType == '7' %}
                                Pago en efectivo
                            {% endif %}
                            {% if polPaymentMethodType == '8' %}
                                Pago Referenciado
                            {% endif %}
                            {% if polPaymentMethodType == '10' %}
                                Pago en bancos
                            {% endif %}
                        </td>
                    </tr>


                </tbody>
            </table>
            {% if ref == 'DO'%}
                <a class="btn btn-action" href="{% url 'webclient:user-documents' %}">Ir mis documentos</a>
                {% if identifier %}
                    {% if transactionState == "4" %}
                    <a class="btn btn-action" href="{% url 'webclient:user-document' identifier %}">Editar mi documento</a>
                    {% endif %}
                {% endif %}
            {% else %}
                <a class="btn btn-action" href="{% url 'webclient:user-documents' %}">Ir mis documentos</a>
            {% endif %}
            </form>

        </div>
    </div>
</main>

{% endblock %}

{% block nav-script%}
{% endblock %}