config/urls.py
from django.conf import settings
from django.urls import include, path
from django.conf.urls.static import static
from django.contrib import admin
from django.views import defaults as default_views


urlpatterns = [

    # Admin
    path('jet/', include('jet.urls', 'jet')),
    path('jet/dashboard/', include('jet.dashboard.urls', 'jet-dashboard')),
    path(settings.ADMIN_URL, admin.site.urls),

    path("accounts/", include("allauth.urls")),
    path('auth/', include('rest_auth.urls')),
    path('auth/registration/', include('rest_auth.registration.urls')),

    path('', include('tratum.webclient.urls'), name='webclient'),
    path('api/', include('tratum.api.urls'), name="api"),
    path('business-info/', include('tratum.business_info.urls'), name='business_info'),
    path('chaining/', include('smart_selects.urls')),
    path('document-manager/', include('tratum.document_manager.urls'), name='document_manager'),
    path('reports/', include('tratum.reports.urls', namespace='reports')),
    path('store/', include('tratum.store.urls'), name='store'),
    path('users/', include('tratum.users.urls'), name='users'),

] + static(
    settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
)

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

tratum/api/urls.py
# -*- coding: utf-8 -*-
from django.urls import path, include
from . import views

app_name = 'api'
urlpatterns = [
    path('api-key/', views.ApiKeyDetailView.as_view(), name='api-key'),
    path('users/', include('tratum.users.urls'), name='users'),
    path('document-manager/', include('tratum.document_manager.urls'), name='document_manager'),
    path('store/', include('tratum.store.urls'), name='store')
]

tratum/store/urls.py
from django.urls import path

from . import views

app_name = 'store'

urlpatterns = [
    path(
        'document-bundles/',
        views.DocumentBundleList.as_view(),
        name='document-bundles'
    ),
    path(
        'create-user-document/',
        views.CreateUserDocument.as_view(),
        name='create-user-document'
    ),
    path(
        'create-user-bundle/',
        views.CreateUserBundle.as_view(),
        name='create_user_bundle'
    ),
    path(
        'user-document/<slug:identifier>/',
        views.UserDocumentDetailView.as_view(),
        name='user-document'
    ),
    path(
        'checkout/',
        views.Checkout.as_view(),
        name='checkout'
    ),
    path(
        'confirmation/',
        views.Checkout.confirmation,
        name='checkout-confirmation'
    ),
]

tratum/users/urls.py
# -*- coding: utf-8 -*-
from django.urls import path

from .views import (
    CompanyUpdate,
    FacebookAuth,
    GoogleAuth,
    SectorList,
    UserChangeEmail,
    UserChangePassword,
    UserDetail,
    UserNameUpdate,
    UserProfessionUpdate
)

app_name = 'users'

urlpatterns = [
    path('auth/facebook/', FacebookAuth.as_view(), name='fb_login'),
    path('auth/google/', GoogleAuth.as_view(), name='gl_login'),
    path('auth/user/', UserDetail.as_view(), name='user-detail'),
    path('profile/<int:pk>/', UserNameUpdate.as_view(), name='user_name_update'),
    path('profile/profession/', UserProfessionUpdate.as_view(), name='user_profession_update'),
    path('change-email/', UserChangeEmail.as_view(), name='user_change_email'),
    path('change-password/', UserChangePassword.as_view(), name='user_change_password'),
    path('sectors/', SectorList.as_view(), name='sector_list'),
    path('company-update/', CompanyUpdate.as_view(), name='company_update'),
]

tratum/webclient/urls.py
import mptt_urls

from django.conf.urls import url
from django.contrib.auth import views as auth_views
from django.urls import path
from . import views

from tratum.document_manager.models import Category
from tratum.document_manager.views import category


app_name = 'webclient'
urlpatterns = [
    path(
        '',
        views.HomePageView.as_view(),
        name='home'
    ),
    path(
        'login/',
        views.LoginView.as_view(),
        name='login'
    ),
    path(
        'logout/',
        auth_views.LogoutView.as_view(next_page="/"),
        name='logout'
    ),
    path(
        'signup/',
        views.SignupView.as_view(),
        name='signup'
    ),
    path(
        'policies/<str:type>/',
        views.PoliciesView.as_view(),
        name='policies'
    ),
    path(
        'validate-terms/',
        views.ValidateTerms.as_view(),
        name="validate-terms"
    ),
    path(
        'faq/',
        views.FAQView.as_view(),
        name="faq"
    ),
    path(
        'glosario/',
        views.GlossaryView.as_view(),
        name="glossary"
    ),
    path(
        'about-us/',
        views.AboutUsView.as_view(),
        name='about-us'
    ),
    path(
        'my-documents/<slug:identifier>/edit/',
        views.UserDocumentView.as_view(),
        name='user-document'
    ),
    path(
        'my-documents/<slug:identifier>/process/',
        views.UserDocumentProcessPreviewView.as_view(),
        name='user-document-process'
    ),
    path(
        'my-documents/<slug:identifier>/preview/',
        views.UserDocumentPreviewView.as_view(),
        name='user-document-preview'
    ),
    path(
        'profile/',
        views.ProfileView.as_view(),
        name='profile'
    ),
    path(
        'my-documents/',
        views.UserDocumentsView.as_view(),
        name='user-documents'
    ),
    path(
        'activate/<token>/<pk>/',
        views.activate,
        name='activate'
    ),
    path(
        'contact-form/',
        views.ContactFormView.as_view(),
        name='contact-form'
    ),
    url(
        r'^documents/(?P<path>.*)',
        mptt_urls.view(model=Category, view=category, slug_field='slug'),
        name='category_documents'
    ),
    path(
        'creacion-empresa/',
        views.CreacionEmpresa.as_view(),
        name="creacion_empresa"
    ),
    path(
        'gestion-contractual/',
        views.GestionContractual.as_view(),
        name="gestion_contractual"
    ),
    path(
        'gestion-empresarial/',
        views.GestionEmpresarial.as_view(),
        name="gestion_empresarial"
    ),
    path(
        'negocios-asuntos-personales/',
        views.NegociosAsuntosPersonales.as_view(),
        name="negocios_asuntos_personales"
    ),
    path(
        'contact-form-landing/',
        views.send_contact_email,
        name="contact_form_email"
    ),
    path(
        'register-form-landing/',
        views.send_register_email,
        name="register_email"
    ),
    path(
        'registro-evento/',
        views.LandingForm.as_view(),
        name="landing_form"
    ),
    path('plans', views.SubscriptionList.as_view(), name='plans')
]

tratum/api/models.py
# -*- coding: utf-8 -*-
import uuid
from django.db import models


class APIKey(models.Model):
    """
    Clase para manejar las restricciones en las API's
    """

    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)

    name = models.CharField(max_length=50, unique=True)
    key = models.CharField(max_length=40, unique=True)

    class Meta:
        verbose_name = "Llave de API"
        verbose_name_plural = "Llaves de API"
        ordering = ['-created']
        app_label = "api"

    def __str__(self):
        return self.name

tratum/reports/models.py
from tratum.document_manager.models import Document, Category
from tratum.store.models import DocumentBundle, Invoice


class DocumentSaleSummary(Document):
    class Meta:
        proxy = True
        verbose_name = 'Reporte de venta de documentos'
        verbose_name_plural = 'Reportes de venta de documentos'


class UserDocumentsSummary(Invoice):
    class Meta:
        proxy = True
        verbose_name = 'Reporte de compras de documentos de clientes'
        verbose_name_plural = 'Reportes de compras de documentos de clientes'


class CategorySaleSummary(Category):
    class Meta:
        proxy = True
        verbose_name = 'Reporte de ventas documentos por categoría'
        verbose_name_plural = 'Reportes de ventas documentos por categoría'


class BundleSaleSummary(DocumentBundle):
    class Meta:
        proxy = True
        verbose_name = 'Reporte de ventas de paquetes'
        verbose_name_plural = 'Reportes de ventas de paquetes'

tratum/business_info/forms.py
from django import forms
from django.core.files.images import get_image_dimensions
from .models import SliderItem, SiteConfig


class SliderItemForm(forms.ModelForm):

    class Meta:
        model = SliderItem
        fields = '__all__'

    def clean_image(self):
        picture = self.cleaned_data.get("image")
        if not picture:
            raise forms.ValidationError("La imagen es requerida")
        else:
            w, h = get_image_dimensions(picture)
            if w != 1920:
                raise forms.ValidationError("La imagen tiene un ancho de %i pixels, se requieren 1920 pixeles." % w)
            if h != 1080:
                raise forms.ValidationError("La imagen tiene un alto de %i pixels, se requieren 1080 pixeles" % h)
        return picture


class SiteConfigForm(forms.ModelForm):

    class Meta:
        model = SiteConfig
        fields = '__all__'

    def clean_about_page_image(self):
        picture = self.cleaned_data.get("about_page_image")
        if not picture:
            raise forms.ValidationError("La imagen es requerida")
        else:
            w, h = get_image_dimensions(picture)
            if w != 800:
                raise forms.ValidationError("La imagen tiene un ancho de %i pixels, se requieren 800 pixeles." % w)
            if h != 1000:
                raise forms.ValidationError("La imagen tiene un alto de %i pixels, se requieren 1000 pixeles" % h)
        return picture

tratum/api/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from rest_framework import generics, status
from rest_framework.permissions import AllowAny
from rest_framework.response import Response
from .models import APIKey
from .serializers import ApiKeySerializer


class ApiKeyDetailView(generics.ListAPIView):
    """
    API para obtener la api key
    """

    serializer_class = ApiKeySerializer
    permission_classes = (AllowAny,)

    def get(self, request, format=None):
        if APIKey.objects.filter(name='web').exists():
            serializer = ApiKeySerializer(APIKey.objects.get(name='web'), many=False)
        else:
            return Response({
                'detail': 'Ocurrió un error al obtener el objeto'
            }, status=status.HTTP_500_INTERNAL_SERVER_ERROR)
        return Response(serializer.data)

tratum/business_info/views.py
from rest_framework import generics

from .models import (
    Policy,
    FAQCategory
)
from .serializers import (
    PolicySerializer,
    FAQCategorySerializer
)


class PolicyList(generics.ListAPIView):
    queryset = Policy.objects.all()
    serializer_class = PolicySerializer


class FAQCategoryList(generics.ListAPIView):
    queryset = FAQCategory.objects.all()
    serializer_class = FAQCategorySerializer

tratum/reports/views.py
from io import BytesIO
import json

from django.http import HttpResponse

from django.template.loader import get_template
from django.views.generic.base import View

from xhtml2pdf import pisa

from .resources import (
    DocumentResource,
    CategoryResource,
    DocumentBundleResource,
    InvoiceResource
)


class DocumentExport(View):

    def post(self, request, *args, **kwargs):
        resource = DocumentResource()
        dataset = resource.export()
        if request.POST.get('CSV', None):
            export_type = dataset.csv
            content_type = 'text/csv'
            format = 'csv'
        elif request.POST.get('XLS', None):
            export_type = dataset.xls
            content_type = 'application/vnd.ms-excel'
            format = 'xls'
        elif request.POST.get('PDF', None):
            template_path = 'admin/document_reports/pdf_skeleton.html'

            context = {
                'summary': json.loads(dataset.json)
            }

            template = get_template(template_path)
            html = template.render(context)

            result = BytesIO()
            pdf = pisa.pisaDocument(BytesIO(html.encode("utf-8")), dest=result)
            if not pdf.err:
                return HttpResponse(result.getvalue(), content_type='application/pdf')
            else:
                return HttpResponse('Errors')

        response = HttpResponse(export_type, content_type=content_type)
        response['Content-Disposition'] = 'attachment; filename="report.{}"'.format(format)
        return response


class CategoryExport(View):

    def post(self, request, *args, **kwargs):
        resource = CategoryResource()
        dataset = resource.export()
        if request.POST.get('CSV', None):
            export_type = dataset.csv
            content_type = 'text/csv'
            format = 'csv'
        elif request.POST.get('XLS', None):
            export_type = dataset.xls
            content_type = 'application/vnd.ms-excel'
            format = 'xls'
        elif request.POST.get('PDF', None):
            template_path = 'admin/category_reports/pdf_skeleton.html'

            context = {
                'summary': json.loads(dataset.json)
            }

            template = get_template(template_path)
            html = template.render(context)

            result = BytesIO()
            pdf = pisa.pisaDocument(BytesIO(html.encode("utf-8")), dest=result)
            if not pdf.err:
                return HttpResponse(result.getvalue(), content_type='application/pdf')
            else:
                return HttpResponse('Errors')

        response = HttpResponse(export_type, content_type=content_type)
        response['Content-Disposition'] = 'attachment; filename="report.{}"'.format(format)
        return response


class DocumentBundleExport(View):

    def post(self, request, *args, **kwargs):
        resource = DocumentBundleResource()
        dataset = resource.export()
        if request.POST.get('CSV', None):
            export_type = dataset.csv
            content_type = 'text/csv'
            format = 'csv'
        elif request.POST.get('XLS', None):
            export_type = dataset.xls
            content_type = 'application/vnd.ms-excel'
            format = 'xls'
        elif request.POST.get('PDF', None):
            template_path = 'admin/bundle_reports/pdf_skeleton.html'

            context = {
                'summary': json.loads(dataset.json)
            }

            template = get_template(template_path)
            html = template.render(context)

            result = BytesIO()
            pdf = pisa.pisaDocument(BytesIO(html.encode("utf-8")), dest=result)
            if not pdf.err:
                return HttpResponse(result.getvalue(), content_type='application/pdf')
            else:
                return HttpResponse('Errors')

        response = HttpResponse(export_type, content_type=content_type)
        response['Content-Disposition'] = 'attachment; filename="report.{}"'.format(format)
        return response


class InvoiceExport(View):

    def post(self, request, *args, **kwargs):
        resource = InvoiceResource()
        dataset = resource.export()
        if request.POST.get('CSV', None):
            export_type = dataset.csv
            content_type = 'text/csv'
            format = 'csv'
        elif request.POST.get('XLS', None):
            export_type = dataset.xls
            content_type = 'application/vnd.ms-excel'
            format = 'xls'
        elif request.POST.get('PDF', None):
            template_path = 'admin/user_reports/pdf_skeleton.html'

            context = {
                'summary': json.loads(dataset.json)
            }

            template = get_template(template_path)
            html = template.render(context)

            result = BytesIO()
            pdf = pisa.pisaDocument(BytesIO(html.encode("utf-8")), dest=result)
            if not pdf.err:
                return HttpResponse(result.getvalue(), content_type='application/pdf')
            else:
                return HttpResponse('Errors')

        response = HttpResponse(export_type, content_type=content_type)
        response['Content-Disposition'] = 'attachment; filename="report.{}"'.format(format)
        return response

tratum/utils/views.py
from django.contrib.auth.tokens import PasswordResetTokenGenerator
from django.utils import six


class AccountActivationTokenGenerator(PasswordResetTokenGenerator):
    def _make_hash_value(self, user, timestamp):
        return (
            six.text_type(user.pk) + six.text_type(timestamp) +
            six.text_type(user.email)
        )

account_activation_token = AccountActivationTokenGenerator()

tratum/templates/landings/creacion_empresa.html
{% extends 'landings/base.html' %}

tratum/templates/landings/gestion_contractual.html
{% extends 'landings/base.html' %}

{% load static %}

{% block title %}
  <title>Gestión contractual | tratum</title>
{% endblock %}

{% block rel-links %}
  <link rel="canonical" href="/gestion-contractual/" />
  <link rel='shortlink' href='/?p=222' />
{% endblock %}

{% block nav %}

  <nav id="top-menu-nav">
    <ul id="top-menu" class="nav">
      <li id="menu-item-52" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-52">
        <a href="{% url 'webclient:creacion_empresa' %}">Creación de empresa</a>
      </li>
      <li id="menu-item-272" class="menu-item menu-item-type-post_type menu-item-object-page current-menu-item page_item page-item-222 current_page_item menu-item-272">
        <a href="{% url 'webclient:gestion_contractual' %}" aria-current="page">Gestión contractual</a>
      </li>
      <li id="menu-item-273" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-273">
        <a href="{% url 'webclient:gestion_empresarial' %}">Gestión empresarial</a>
      </li>
      <li id="menu-item-287" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-287">
        <a href="{% url 'webclient:negocios_asuntos_personales' %}">Negocios y asuntos personales</a>
      </li>
    </ul>
  </nav>
{% endblock %}

{% block content-id %}id="post-222" class="post-222 page type-page status-publish hentry" {% endblock %}>

{% block promo-description %}
  <h1 class="et_pb_module_header">¿Necesitas un contrato correctamente elaborado? </h1>
  <p>Con <strong>tratum </strong>hazlo legalmente fácil y rápido </p>
{% endblock %}

{% block tratum-facil %}
  <p>Te ayudamos para que crees tus contratos laborales, renovaciones y demás contratos legales que mantendrán tu empresa en regla.</p>
{% endblock %}

{% block text-inner %}
  <p>CREA CORRECTAMENTE <h style="color: #F0CD21;">TUS CONTRATOS </h> AHORA MISMO!!</p>
{% endblock %}

{% block paralax-bg %}
  <span
    class="et_parallax_bg"
    style="background-image: url({% static 'wp-content/uploads/2019/07/contratos-legales-1.jpg' %});"
  ></span>
{% endblock %}

{% block documents-title %}
  <h2> Tipos de contratos </h2>
{% endblock %}


{% block document-list %}
  <div class="et_pb_column et_pb_column_1_3 et_pb_column_5  et_pb_css_mix_blend_mode_passthrough">
    <div class="et_pb_with_border et_pb_module et_pb_text et_pb_text_3 et_animated et_pb_bg_layout_dark  et_pb_text_align_left">
      <div class="et_pb_text_inner">
        <div style="padding:20px">
          <h4>Creacion de empresa</h4>
          <h2>Acto constitutivo</h2>
          <p>Sencillo, para el crecimiento de las empresas/emprendimientos es clave tener todo claro y por escrito.</p>
        </div>
        <div style="background:#DDDDDD;5px; padding:10px">
          <h style="color:#002C55;"><center><b>Valor: $300.000</b></center></h></div>
      </div>
    </div> <!-- .et_pb_text -->
  </div> <!-- .et_pb_column -->
  <div class="et_pb_column et_pb_column_1_3 et_pb_column_6  et_pb_css_mix_blend_mode_passthrough">
    <div class="et_pb_with_border et_pb_module et_pb_text et_pb_text_4 et_animated et_pb_bg_layout_dark  et_pb_text_align_left">


      <div class="et_pb_text_inner">
        <div style="padding:20px">
          <h4>Creacion de empresa</h4>
          <h2>Acto constitutivo</h2>
          <p>Sencillo, para el crecimiento de las empresas/emprendimientos es clave tener todo claro y por escrito.</p>
        </div>
        <div style="background:#DDDDDD;5px; padding:10px">
          <h style="color:#002C55;"><center><b>Valor: $300.000</b></center></h></div>
      </div>
    </div> <!-- .et_pb_text -->
  </div> <!-- .et_pb_column -->
  <div class="et_pb_column et_pb_column_1_3 et_pb_column_7  et_pb_css_mix_blend_mode_passthrough">
    <div class="et_pb_with_border et_pb_module et_pb_text et_pb_text_5 et_animated et_pb_bg_layout_dark  et_pb_text_align_left">
      <div class="et_pb_text_inner">
        <div style="padding:20px">
          <h4>Creacion de empresa</h4>
          <h2>Acto constitutivo</h2>
          <p>Sencillo, para el crecimiento de las empresas/emprendimientos es clave tener todo claro y por escrito.</p>
        </div>
        <div style="background:#DDDDDD;5px; padding:10px">
          <h style="color:#002C55;"><center><b>Valor: $300.000</b></center></h></div>
      </div>
    </div> <!-- .et_pb_text -->
  </div> <!-- .et_pb_column -->
{% endblock %}

tratum/templates/landings/gestion_empresarial.html
{% extends 'landings/base.html' %}

{% load static %}

{% block title %}
  <title>Gestión Empresarial | tratum</title>
{% endblock %}

{% block rel-links %}
  <link rel="canonical" href="/gestion-empresarial/" />
  <link rel='shortlink' href='/?p=222' />
{% endblock %}

{% block nav %}

  <nav id="top-menu-nav">
    <ul id="top-menu" class="nav">
      <li id="menu-item-52" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-52">
        <a href="{% url 'webclient:creacion_empresa' %}">Creación de empresa</a>
      </li>
      <li id="menu-item-272" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-272">
        <a href="{% url 'webclient:gestion_contractual' %}" >Gestión contractual</a>
      </li>
      <li id="menu-item-273" class="menu-item menu-item-type-post_type menu-item-object-page current-menu-item page_item page-item-255 current_page_item menu-item-273">
        <a href="{% url 'webclient:gestion_empresarial' %}" aria-current="page">Gestión empresarial</a>
      </li>
      <li id="menu-item-287" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-287">
        <a href="{% url 'webclient:negocios_asuntos_personales' %}">Negocios y asuntos personales</a>
      </li>
    </ul>
  </nav>
{% endblock %}

{% block content-id %}id="post-255" class="post-255 page type-page status-publish hentry" {% endblock %}>

{% block promo-description %}
  <h1 class="et_pb_module_header">¿Quieres gestionar correctamente los procesos internos de tu empresa correctamente?</h1>
  <p>Con <strong>tratum </strong>hazlo legalmente rápido y fácil.</p>
{% endblock %}

{% block tratum-facil %}
  <p>Te ayudamos a estructurar tus proceso de la mejor manera posible con nosotros tienes el orden que necesitas.</p>
{% endblock %}

{% block text-inner %}
  <p>ORDENATE AHORA MISMO <h style="color: #F0CD21;">Y LIDERA</h> TRANQUILO!!</p>
{% endblock %}

{% block paralax-bg %}
  <span
    class="et_parallax_bg"
    style="background-image: url({% static 'wp-content/uploads/2019/07/reuniones-laborales.jpg' %});"
  ></span>
{% endblock %}

{% block documents-title %}
  <h2> Procesos en los que te ayudaremos </h2>
{% endblock %}

tratum/templates/landings/negocios_asuntos_personales.html
{% extends 'landings/base.html' %}

{% load static %}

{% block title %}
  <title>Negocios y asuntos personales | tratum</title>
{% endblock %}

{% block rel-links %}
  <link rel="canonical" href="/negocios-asuntos-personales/" />
  <link rel='shortlink' href='/?p=274' />
{% endblock %}

{% block nav %}

  <nav id="top-menu-nav">
    <ul id="top-menu" class="nav">
      <li id="menu-item-52" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-52">
        <a href="{% url 'webclient:creacion_empresa' %}">Creación de empresa</a>
      </li>
      <li id="menu-item-272" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-272">
      <a href="{% url 'webclient:gestion_contractual' %}" >Gestión contractual</a>
    </li>
      <li id="menu-item-273" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-273">
        <a href="{% url 'webclient:gestion_empresarial' %}">Gestión empresarial</a>
      </li>
      <li id="menu-item-287" class="menu-item menu-item-type-post_type menu-item-object-page current-menu-item page_item page-item-274 current_page_item menu-item-287">
        <a href="{% url 'webclient:negocios_asuntos_personales' %}" aria-current="page">Negocios y asuntos personales</a>
      </li>
    </ul>
  </nav>
{% endblock %}

{% block content-id %}id="post-274" class="post-274 page type-page status-publish hentry" {% endblock %}>

{% block promo-description %}
  <h1 class="et_pb_module_header">¿Te haz preguntado como gestionar tus asuntos personales?</h1>
  <p>Con <strong>tratum </strong>hazlo legalmente fácil y rápido </p>
{% endblock %}

{% block tratum-facil %}
  <p>te ayudaremos a ordenar siempre y estructurar de la mejor manera todos contratos y procesos que necesitas para tener tu día a día tranquilo. </p>
{% endblock %}

{% block text-inner %}
  <p>GESTIONA LO QUE HACES <h style="color: #F0CD21;">CON NOSOTROS</h> AHORA MISMO!!</p>
{% endblock %}

{% block paralax-bg %}
  <span
    class="et_parallax_bg"
    style="background-image: url({% static 'wp-content/uploads/2019/07/asuntos-y-negocios.jpg' %});"
  ></span>
{% endblock %}

{% block documents-title %}
  <h2> Procesos en los que te ayudaremos </h2>
{% endblock %}