config/urls.py
from django.conf import settings
from django.urls import include, path
from django.conf.urls.static import static
from django.contrib import admin
from django.views import defaults as default_views


urlpatterns = [

    # Admin
    path('jet/', include('jet.urls', 'jet')),
    path('jet/dashboard/', include('jet.dashboard.urls', 'jet-dashboard')),
    path(settings.ADMIN_URL, admin.site.urls),

    path("accounts/", include("allauth.urls")),
    path('auth/', include('rest_auth.urls')),
    path('auth/registration/', include('rest_auth.registration.urls')),

    path('', include('tratum.webclient.urls'), name='webclient'),
    path('api/', include('tratum.api.urls'), name="api"),
    path('business-info/', include('tratum.business_info.urls'), name='business_info'),
    path('chaining/', include('smart_selects.urls')),
    path('document-manager/', include('tratum.document_manager.urls'), name='document_manager'),
    path('reports/', include('tratum.reports.urls', namespace='reports')),
    path('store/', include('tratum.store.urls'), name='store'),
    path('users/', include('tratum.users.urls'), name='users'),

] + static(
    settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
)

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

tratum/api/urls.py
# -*- coding: utf-8 -*-
from django.urls import path, include
from . import views

app_name = 'api'
urlpatterns = [
    path('api-key/', views.ApiKeyDetailView.as_view(), name='api-key'),
    path('users/', include('tratum.users.urls'), name='users'),
    path('document-manager/', include('tratum.document_manager.urls'), name='document_manager'),
    path('store/', include('tratum.store.urls'), name='store')
]

tratum/document_manager/urls.py
from django.urls import path

from .views import (
    DocumentFieldList,
    DocumentFieldDetail,
    DocumentSectionList,
    DocumentSectionDetail,
    DocumentSectionFieldsList,
    ProcessDocumentView,
    SaveAnswersView,
    DocumentList,
    CategoryRootList,
    CategoryChildrenList,
    FinishDocumentView,
    UserDocumentContentView,
    MainDocumentList,
    LinkedFieldView,
    ChangeAdminOrder,
    ChangeAdminOptionOrder
)

app_name = 'document_manager'

urlpatterns = [
    path(
        'document-fields/',
        DocumentFieldList.as_view(),
        name='document-fields'
    ),
    path(
        'document-fields/<slug:slug>/',
        DocumentFieldDetail.as_view(),
        name='document-field'
    ),
    path(
        'document-sections/',
        DocumentSectionList.as_view(),
        name='document-sections'
    ),
    path(
        'document-sections/<slug:slug>/',
        DocumentSectionDetail.as_view(),
        name='document-section'
    ),
    path(
        'document-sections/<slug:slug>/section-fields/',
        DocumentSectionFieldsList.as_view(),
        name='document-section-fields'
    ),
    path(
        'document-options/<int:pk>/linked-fields/',
        LinkedFieldView.as_view(),
        name='document-option'
    ),
    path(
        'finish/',
        FinishDocumentView.as_view(),
        name='finish'
    ),
    path(
        'process/',
        ProcessDocumentView.as_view(),
        name='process'
    ),
    path(
        'save-preview/',
        SaveAnswersView.as_view(),
        name='save-preview'
    ),
    path(
        'form-preview/',
        UserDocumentContentView.as_view(),
        name='form-preview'
    ),
    path(
        'finish/',
        FinishDocumentView.as_view(),
        name='finish'
    ),
    path(
        'documents/',
        MainDocumentList.as_view(),
        name='main-document-list'
    ),
    path(
        'documents/<slug:slug>/',
        DocumentList.as_view(),
        name='document-list'
    ),
    path(
        'categories/',
        CategoryRootList.as_view(),
        name='categories-root-list'
    ),
    path(
        'change-admin-order/',
        ChangeAdminOrder.as_view(),
        name='change-admin-order'
    ),
    path(
        'change-admin-option-order/',
        ChangeAdminOptionOrder.as_view(),
        name='change-admin-option-order'
    ),
    path(
        'categories/<slug:slug>/children/',
        CategoryChildrenList.as_view(),
        name='categories-children-list'
    ),
]

tratum/store/urls.py
from django.urls import path

from . import views

app_name = 'store'

urlpatterns = [
    path(
        'document-bundles/',
        views.DocumentBundleList.as_view(),
        name='document-bundles'
    ),
    path(
        'create-user-document/',
        views.CreateUserDocument.as_view(),
        name='create-user-document'
    ),
    path(
        'create-user-bundle/',
        views.CreateUserBundle.as_view(),
        name='create_user_bundle'
    ),
    path(
        'user-document/<slug:identifier>/',
        views.UserDocumentDetailView.as_view(),
        name='user-document'
    ),
    path(
        'checkout/',
        views.Checkout.as_view(),
        name='checkout'
    ),
    path(
        'confirmation/',
        views.Checkout.confirmation,
        name='checkout-confirmation'
    ),
]

tratum/users/urls.py
# -*- coding: utf-8 -*-
from django.urls import path

from .views import (
    CompanyUpdate,
    FacebookAuth,
    GoogleAuth,
    SectorList,
    UserChangeEmail,
    UserChangePassword,
    UserDetail,
    UserNameUpdate,
    UserProfessionUpdate
)

app_name = 'users'

urlpatterns = [
    path('auth/facebook/', FacebookAuth.as_view(), name='fb_login'),
    path('auth/google/', GoogleAuth.as_view(), name='gl_login'),
    path('auth/user/', UserDetail.as_view(), name='user-detail'),
    path('profile/<int:pk>/', UserNameUpdate.as_view(), name='user_name_update'),
    path('profile/profession/', UserProfessionUpdate.as_view(), name='user_profession_update'),
    path('change-email/', UserChangeEmail.as_view(), name='user_change_email'),
    path('change-password/', UserChangePassword.as_view(), name='user_change_password'),
    path('sectors/', SectorList.as_view(), name='sector_list'),
    path('company-update/', CompanyUpdate.as_view(), name='company_update'),
]

tratum/webclient/urls.py
import mptt_urls

from django.conf.urls import url
from django.contrib.auth import views as auth_views
from django.urls import path
from . import views

from tratum.document_manager.models import Category
from tratum.document_manager.views import category


app_name = 'webclient'
urlpatterns = [
    path(
        '',
        views.HomePageView.as_view(),
        name='home'
    ),
    path(
        'login/',
        views.LoginView.as_view(),
        name='login'
    ),
    path(
        'logout/',
        auth_views.LogoutView.as_view(next_page="/"),
        name='logout'
    ),
    path(
        'signup/',
        views.SignupView.as_view(),
        name='signup'
    ),
    path(
        'policies/<str:type>/',
        views.PoliciesView.as_view(),
        name='policies'
    ),
    path(
        'validate-terms/',
        views.ValidateTerms.as_view(),
        name="validate-terms"
    ),
    path(
        'faq/',
        views.FAQView.as_view(),
        name="faq"
    ),
    path(
        'glosario/',
        views.GlossaryView.as_view(),
        name="glossary"
    ),
    path(
        'about-us/',
        views.AboutUsView.as_view(),
        name='about-us'
    ),
    path(
        'my-documents/<slug:identifier>/edit/',
        views.UserDocumentView.as_view(),
        name='user-document'
    ),
    path(
        'my-documents/<slug:identifier>/process/',
        views.UserDocumentProcessPreviewView.as_view(),
        name='user-document-process'
    ),
    path(
        'my-documents/<slug:identifier>/preview/',
        views.UserDocumentPreviewView.as_view(),
        name='user-document-preview'
    ),
    path(
        'profile/',
        views.ProfileView.as_view(),
        name='profile'
    ),
    path(
        'my-documents/',
        views.UserDocumentsView.as_view(),
        name='user-documents'
    ),
    path(
        'activate/<token>/<pk>/',
        views.activate,
        name='activate'
    ),
    path(
        'contact-form/',
        views.ContactFormView.as_view(),
        name='contact-form'
    ),
    url(
        r'^documents/(?P<path>.*)',
        mptt_urls.view(model=Category, view=category, slug_field='slug'),
        name='category_documents'
    ),
    path(
        'creacion-empresa/',
        views.CreacionEmpresa.as_view(),
        name="creacion_empresa"
    ),
    path(
        'gestion-contractual/',
        views.GestionContractual.as_view(),
        name="gestion_contractual"
    ),
    path(
        'gestion-empresarial/',
        views.GestionEmpresarial.as_view(),
        name="gestion_empresarial"
    ),
    path(
        'negocios-asuntos-personales/',
        views.NegociosAsuntosPersonales.as_view(),
        name="negocios_asuntos_personales"
    ),
    path(
        'contact-form-landing/',
        views.send_contact_email,
        name="contact_form_email"
    ),
    path(
        'register-form-landing/',
        views.send_register_email,
        name="register_email"
    ),
    path(
        'registro-evento/',
        views.LandingForm.as_view(),
        name="landing_form"
    ),
    path('plans', views.SubscriptionList.as_view(), name='plans')
]

tratum/business_info/models.py
from django.db import models
from django.core.exceptions import ValidationError

from tratum.ckeditor.fields import RichTextField


class Policy(models.Model):
    """Guarda las políticas de la plataforma

    Campos del modelo:
        content: Contenido de la política
        last_update_date: Indica cuando se realizó la última actualización del registro
        police_type: Tipo de política, sólo puede existir un registro por tipo

    """

    TERMS_AND_CONDITIONS = 'TCP'
    PRIVACY = 'PP'
    COOKIES_MANAGEMENT = 'CMP'

    POLICY_TYPE = (
        (TERMS_AND_CONDITIONS, 'Términos y condiciones'),
        (PRIVACY, 'Política de privacidad y tratamiento de datos'),
        (COOKIES_MANAGEMENT, 'Política de tratamiento de Cookies'),
    )

    content = RichTextField('Contenido')
    last_update_date = models.DateTimeField(
        'Fecha de última actualización',
        auto_now_add=True
    )
    policy_type = models.CharField(
        "Tipo de Política",
        max_length=3,
        choices=POLICY_TYPE,
        unique=True
    )

    def __str__(self):
        return "%s" % (self.policy_type)

    class Meta:
        verbose_name = "Politica"


class FAQCategory(models.Model):
    """Guarda las categorías de las preguntas frecuentes

    Campos del modelo:
        name: Nombre de la categoría

    """

    name = models.CharField(
		'Nombre',
        max_length=30,
        unique=True
    )

    class Meta:
        verbose_name = 'FAQ'

    def __str__(self):
        return self.name


class FAQItem(models.Model):
    """Guardas las preguntas frecuentes, por categoria

    Campos del modelo:
        category: Llave foránea nula a categoría
        question: Texto de la pregunta
        answer: Texto de la respuesta

    """

    category = models.ForeignKey(
        FAQCategory,
        models.SET_NULL,
        null=True,
        blank=True
    )
    question = models.TextField('Pregunta', unique=True)
    answer = models.TextField('Respuesta', unique=True)

    class Meta:
        verbose_name = 'Item de categoria'
        verbose_name_plural = 'Items de categoria'

    def __str__(self):
        return self.question


class GlossaryCategory(models.Model):
    """Guarda las categorías del Glosario

    Campos del modelo:
        name: Nombre de la categoría

    """

    name = models.CharField(
        'Nombre',
        max_length=30,
        unique=True
    )

    class Meta:
        verbose_name = 'Glosario'

    def __str__(self):
        return self.name


class GlossaryItem(models.Model):
    """Guardas las entradas del glosario, por categoria

    Campos del modelo:
        category: Llave foránea nula a categoría
        word: Palabra
        meaning: Texto del significado

    """

    category = models.ForeignKey(
        GlossaryCategory,
        models.SET_NULL,
        null=True,
        blank=True
    )
    word = models.CharField('Palabra', max_length=100, unique=True)
    meaning = models.TextField('Significado')

    class Meta:
        verbose_name = 'Item de glosario'
        verbose_name_plural = 'Items de glosario'
        ordering = ['word',]

    def __str__(self):
        return self.word


class SiteConfig(models.Model):
    """Guarda la información del sitio estático (Landing page y quienes sómos)

    Campos del modelo:
        about_page_title: Nombre de la página de Quienes sómos
        about_page_content: Contenido de la página de Quienes sómos
        about_page_image: Imagen de la página de Quienes sómos

    """

    about_page_title = models.CharField(
		'Título (Quienes sómos)',
        max_length=30,
        null=True,
        blank=True
    )
    about_page_content = models.TextField(
		'Contenido (Quienes sómos)',
        max_length=600,
        null=True,
        blank=True
    )
    about_page_image = models.ImageField(
        'Imagen (Quienes somos)',
        null=True,
        blank=True,
        upload_to='about-us',
        help_text='La resolución requerida es de 800x1000px'
    )
    landing_contact = models.TextField(
        'Correo de contacto (landing)',
        null=True,
        blank=True
    )
    landing_phone = models.TextField(
		'Teléfono de contacto (landing)',
        null=True,
        blank=True
    )
    landing_contract_info = models.TextField(
		'¿Por qué construir un contrato responsablemente? (landing)',
        null=True,
        blank=True
    )
    landing_bundles_info = models.TextField(
		'Paquetes(landing)',
        null=True,
        blank=True
    )
    facebook_url = models.URLField(
		'URL Facebook (landing)',
        null=True,
        blank=True
    )
    twitter_url = models.URLField(
		'URL Twitter (landing)',
        null=True,
        blank=True
    )
    instagram_url = models.URLField(
		'URL Instagram (landing)',
        null=True,
        blank=True
    )

    youtube_url = models.URLField(
        'URL Youtube (landing)',
        null=True,
        blank=True
    )

    meta_tags = models.TextField(
		'Tags de SEO y SEM',
        null=True,
        blank=True
    )

    terms_file = models.FileField(
        upload_to='legal',
        blank=True,
        null=True
    )

    terms_file = models.FileField(
        'Documento de términos y condiciones',
        upload_to='legal',
        blank=True,
        null=True
    )

    data_policy_file = models.FileField(
        'Documento de política de tratamiento de datos',
        upload_to='legal',
        blank=True,
        null=True
    )

    class Meta:
        verbose_name = 'Configuración de sitio'
        verbose_name_plural = verbose_name

    def __str__(self):
        return 'Registro de configuración de sitio'

    def clean(self):
        """Retorna ValidationError si se intenta crear más de una instancia
        """

        model = self.__class__
        if (model.objects.count() > 0 and
                self.id != model.objects.get().id):
            raise ValidationError(
                "Sólo se puede crear una instancia de %s." % model.__name__)


class SliderItem(models.Model):
    image = models.ImageField('Imagen', upload_to='slides', help_text='La resolución es 1920 x 1080p')
    text = models.CharField(
        'Texto',
        max_length=255,
        null=True,
        blank=True
    )
    description = models.CharField(
        'Descripción',
        max_length=255,
        null=True,
        blank=True
    )
    youtube_video_link = models.URLField(
        'Link de Youtube',
        blank=True,
        null=True
    )

    class Meta:
        verbose_name = 'Slide del home'
        verbose_name_plural = 'Slides del home'

    def __str__(self):
        return 'Slide '


class MainCategory(models.Model):
    title = models.CharField(
        'Título de categoría',
        max_length=100,
    )
    image = models.ImageField(
        'Imagen',
        upload_to='main_categories',
        help_text='La resolución es 1920 x 1080p'
    )
    description = models.TextField(
        'Descripción',
        null=True,
        blank=True
    )
    button_title = models.CharField(
        'Título de botón (para home)',
        max_length=100
    )
    button_url = models.URLField(
        'URL para botón de categoría'
    )

    class Meta:
        verbose_name = 'Categoría principal'
        verbose_name_plural = 'Categorías principales'

    def __str__(self):
        return 'Slide '

tratum/business_info/views.py
from rest_framework import generics

from .models import (
    Policy,
    FAQCategory
)
from .serializers import (
    PolicySerializer,
    FAQCategorySerializer
)


class PolicyList(generics.ListAPIView):
    queryset = Policy.objects.all()
    serializer_class = PolicySerializer


class FAQCategoryList(generics.ListAPIView):
    queryset = FAQCategory.objects.all()
    serializer_class = FAQCategorySerializer

tratum/templates/webclient/dropdown.html
<a class="dropdown-item" href="#">
    <div class="droprigth subdrop">
        <a
            {% if c.get_children %}
                class="dropdown-toggle"
                data-toggle="dropdown"
                aria-haspopup="true"
                aria-expanded="false"
            {% else %}
                href="{{c.get_absolute_url}}"
            {% endif %}>{{c.name}}
        {% if c.get_children %}
        <span class="toright"></span>
        {% endif %}
        </a>
            {% if c.get_children %}
                <div class="dropdown-menu">
                    {% for c in c.get_children %}
                        {% include 'webclient/dropdown.html' %}
                    {% endfor %}
                </div>
            {% endif %}
    </div>
</a>

tratum/templates/webclient/home.html
{% extends 'webclient/base.html' %}
{% load static %}
{% load humanize %}

{% block extra_css %}
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/easy-autocomplete/1.3.5/easy-autocomplete.min.css" />
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/Swiper/4.3.3/css/swiper.min.css">
  <link rel="stylesheet" href="https://unpkg.com/aos@next/dist/aos.css" />
{% endblock %}

{% block nav_class %}
    class="navbar scrolled fixed-top"
{% endblock %}

{% block menu_custom_class %}hidden{% endblock menu_custom_class %}

{% block content %}
  <div class="modal fade" id="homeVideoModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog large" role="document">
      <i class="fas fa-times-circle" data-dismiss="modal"></i>
      <div class="modal-content">
        <div class="modal-body">
          <iframe width="100%" height="500px" frameborder="0" allow="autoplay; encrypted-media" allowfullscreen></iframe>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Cerrar</button>
        </div>
      </div>
    </div>
  </div>

  <div id="loadingAnimation">
    <img src="{% static 'img/loadingSite.gif' %}" />
    <p>Cargando...</p>
  </div>

  <div class="swiper-container">
    <div class="swiper-wrapper">
      {% for s in context_slides %}
        <div class="swiper-slide">
          <div class="swiper-mask-left"></div>
          <div class="swiper-mask-right"></div>
          <div class="description text-center">
            <h1>{{s.text|default_if_none:""}}</h1>
            <p>{{s.description|default_if_none:""}}</p>
            {% if s.youtube_video_link %}
              <a class="video-trigger" data-toggle="modal" data-target="#homeVideoModal" data-embed="{{s.youtube_video_link}}">
                <i class="fas fa-play-circle"></i>
              </a>
            {% endif %}
          </div>
          <img src="{{s.image.url}}">
        </div>
      {% endfor %}
    </div>
    <div class="swiper-pagination"></div>
    <div class="search-landing">
      <input type="search" placeholder="Busca tus documentos..." id="search_documents">
      <div id="result-list">

      </div>
    </div>
  </div>

  {% for category in main_categories %}
    {% if forloop.counter|divisibleby:2 %}
    <div class="row categories">
      <div class="col-md-6 order-2 order-md-1 category-description left">
          <div class="container">

              <h2>{{ category.title }}</h2>
              <p>{{ category.description }}</p>
              <a class="action-button__primary" href="{{ category.button_url }}">{{ category.button_title }}</a>
          </div>
        </div>
      <div class="col-md-6 order-1 order-md-2 category-parallax" style="background-image: url('{{ category.image.url }}');">
      </div>
    </div>
    {% else %}
    <div class="row categories">
      <div class="col-md-6 order-1 category-parallax" style="background-image: url('{{ category.image.url }}');">
      </div>
      <div class="col-md-6 order-2 category-description">
        <div class="container">
            <h2>{{ category.title }}</h2>
            <p>{{ category.description }}</p>
            <a class="action-button__primary" href="{{ category.button_url }}">{{ category.button_title }}</a>
        </div>
      </div>
    </div>
    {% endif %}

  {% endfor %}

  <div class="row categories how-to">
    <div class="col-md-8 category-description left">
        <div class="container">
            <h2>¿CÓMO CREAR UN DOCUMENTO?</h2>
            <ul>
              <li>
                <span class="indicator">1</span>
                <span>Inicia sesión o regístrate en la plataforma.</span>
              </li>
              <li>
                <span class="indicator">2</span>
                <span>Ingresa a nuestra tienda y selecciona el documento que necesitas.</span>
              </li>
              <li>
                <span class="indicator">3</span>
                <span>Realiza el pago por cualquiera de los canales que tenemos dispuestos para ti.</span>
              </li>
              <li>
                <span class="indicator">4</span>
                <span>Diligencia el formulario del documento de acuerdo a tus necesidades.</span>
              </li>
              <li>
                <span class="indicator">5</span>
                <span>Finaliza el documento cuando hayas terminado y lo enviaremos a tu correo electrónico en formato pdf o .docx.</span>
              </li>
            </ul>
        </div>
      </div>
    <div class="col-md-4">
        <div class="container-flex flex-column justify-content-center" style="padding-right: 25%; padding-top: 15%;">
            <img src="{% static 'img/steps.png' %}" width="100%" />
        </div>

    </div>
  </div>

  <div class="row contract-info p-3">
    <div class="col-md-6">
      <img src="{% static 'img/Web2-40.png' %}" width="100%" />
    </div>
    <div class="col-md-6">
      <div class="container-flex flex-column justify-content-center" style="margin-top: 25px;">
        <h2>¿Por qué construir un contrato responsablemente?</h2>
        <p style="text-align:justify;">{{landing_contract_info|linebreaksbr}}</p>
        <a class="action-button__primary" href="/documents/">Ir a Tienda de documentos</a>
      </div>
    </div>
  </div>


  {% if context_bundles %}
  <div class="row bundles">
    <div class="container">
      <div class="col text-center">
        <div class="container">
            <h2>Paquetes</h2>
            <span class="counter">{{context_bundle_count}} disponibles</span>
            <p>{{ landing_bundles_info|linebreaksbr }}</p>
        </div>
        <div class="row">
          {% for i in context_bundles %}
            <div class="col-lg-4 h-50">
                <div class="bundle
                  {% if forloop.counter == 2 %}
                    dark-blue
                  {% else %}
                    {% if forloop.counter == 3 %}
                      light-yellow
                    {% endif %}
                  {% endif %}">
                  <span class="name">{{i.name}}</span>
                  <span class="pricetag">${{i.price|intcomma}}</span>
                  <div class="documents">
                    <span class="title">Documentos del paquete</span>
                    {% for d in i.documents.all %}
                      <span class="document">{{d.name}}</span>
                    {% endfor %}
                  </div>

                  {% if user.is_authenticated %}
                     {%if i.price is None or i.price == 0%}
                        <form method="GET" action="{% url 'store:create_user_bundle' %}">
                        <input type="hidden" name="pack_id" value="{{i.id}}">
                        <button type="submit" class="btn btn-primary">Comprar</button>
                      </form>
                     {% else %}
                       <form method="GET" action="{% url 'store:checkout' %}">
                        <input type="hidden" name="pack_id" value="{{i.id}}">
                        <button type="submit" class="btn btn-primary">Comprar</button>
                      </form>
                     {% endif %}

                  {% else %}
                    <button data-toggle="modal" data-target="#modal-login" class="btn btn-primary">Comprar</button>
                  {% endif %}
                </div>
            </div>
          {% endfor %}
        </div>
        <div class="row">
          <a class="action-button__primary" href="/documents/?package=true">Ver todos</a>
        </div>
      </div>
    </div>
  </div>
  {% endif %}


  <div class="row contact-form">
    <div class="col text-center">
      <h5 class="text-white">Contáctanos</h5>
      <form id="contact_form" method="POST">
        {% csrf_token %}
        <div class="form-group">
          <input required name="name" type="text" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Nombre" autocomplete="off">
        </div>
        <div class="form-group">
          <input required name="email" type="email" class="form-control" id="exampleInputEmail2" placeholder="Correo electrónico" autocomplete="off">
        </div>
        <div class="form-group">
          <textarea required name="message" class="form-control" placeholder="Mensaje" autocomplete="off"></textarea>
        </div>
        <div class="g-recaptcha" data-sitekey="6LdqLn0UAAAAAKildIXZzJZicplDzL7RJLOomOSr"></div>
        <div class="form-group">
          <button type="submit" id="contact_form_submit" class="action-button__primary">Enviar</button>
        </div>
      </form>
    </div>
  </div>

{% endblock %}

{% block extra_js %}
    <script src="{% static 'js/jquery.disableAutoFill.min.js' %}"></script>
    <script>
      window.onload = function(){ document.getElementById("loadingAnimation").style.display = "none" }
      $("#contact_form").disableAutoFill();
    </script>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/easy-autocomplete/1.3.5/jquery.easy-autocomplete.min.js"></script>
    <script
    src="https://code.jquery.com/color/jquery.color-2.1.2.min.js"
    integrity="sha256-H28SdxWrZ387Ldn0qogCzFiUDDxfPiNIyJX7BECQkDE="
    crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Swiper/4.3.3/js/swiper.min.js"></script>
    <script>
      window.scrollTo(0, 0);




      var mySwiper = new Swiper ('.swiper-container', {
          direction: 'horizontal',
          loop: true,
          navigation: {
            nextEl: '.swiper-button-next',
            prevEl: '.swiper-button-prev',
          },
          pagination: {
            el: '.swiper-pagination',
          },
          autoplay: {
            delay: 5000,
          }
      })

      $('.swiper-mask-left').on('click', function(){
        mySwiper.slidePrev();
      })

      $('.swiper-mask-right').on('click', function(){
        mySwiper.slideNext();
      })

      $('.video-trigger').on('click', function(event) {
        var embedUrl = $(this).data('embed');
        var modal = $('#homeVideoModal');
        modal.find('iframe').attr('src', embedUrl);
      })

      $('.cookiepolicy-close').on('click', function(){
        $('.cookiepolicy-info').hide();
      })

      var list = {
        url: "{% url 'document_manager:main-document-list' %}",
        getValue: "name",
        list: {
          match: {
            enabled: true
          },
          onSelectItemEvent: function() {
            var value = $("#search_documents").getSelectedItemData().name;
            window.location.href = `/documents?q=${value}`
          }
        }
      }

      $("#search_documents").easyAutocomplete(list);

      $('#search_documents').on('keyup', function(e){
        if (e.keyCode === 13) {
          window.location.href = `/documents?q=${$(this).val()}`
        }
      })

      function cookieChecker() {
        if (document.cookie.replace(/(?:(?:^|.*;\s*)cookiePolicyAccepted\s*\=\s*([^;]*).*$)|^.*$/, "$1") !== "true") {
          $('.cookiepolicy-info').show();
          document.cookie = "cookiePolicyAccepted=true; expires=Fri, 31 Dec 9999 23:59:59 GMT";
        }
      }



      cookieChecker();
    </script>
{% endblock %}